<?php

/**
 * @file
 * Contains commerce_payment_dibs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_payment_dibs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_payment_dibs module.
    case 'help.page.commerce_payment_dibs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides dibs payment integration for commerce.') . '</p>';
      return $output;

    default:
  }
}
